# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(editable=False)),
                ('visited_time', models.DateTimeField(editable=False)),
                ('bookmarked_time', models.DateTimeField(editable=False)),
            ],
        ),
    ]
