# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookmarked_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='visited_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
